version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: django
    container_name: lummo-django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12
    container_name: lummo_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.env

  redis:
    image: redis:latest
    container_name: lummo-redis
